"""add owner username to recipes and collection table

Revision ID: ac0bb6a2fc3e
Revises: 525bd23f6a0b
Create Date: 2025-01-23 12:46:04.051628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0bb6a2fc3e'
down_revision = '525bd23f6a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_username', sa.String(), nullable=False))
        batch_op.create_foreign_key('fk_collections_owner_username', 'users', ['owner_username'], ['username'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_username', sa.Text(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_owner_username', 'users', ['owner_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipes_owner_username', type_='foreignkey')
        batch_op.drop_column('owner_username')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_owner_username', type_='foreignkey')
        batch_op.drop_column('owner_username')

    # ### end Alembic commands ###
