"""preview image and image column changes to recipe and recipe image tables

Revision ID: e4e488c10834
Revises: 1fd9850b9b08
Create Date: 2025-01-27 16:01:58.814761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e488c10834'
down_revision = '1fd9850b9b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preview_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('preview_image')
        batch_op.drop_column('images')

    # ### end Alembic commands ###
