"""add owner username to collection recipe

Revision ID: 1fd9850b9b08
Revises: ac0bb6a2fc3e
Create Date: 2025-01-23 19:09:50.741659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd9850b9b08'
down_revision = 'ac0bb6a2fc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_username', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_owner_username', 'users', ['owner_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_recipes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_owner_username', type_='foreignkey')
        batch_op.drop_column('owner_username')

    # ### end Alembic commands ###
